### ISSUE TITLE
[Bug] Custom text & Health Text have different z-layers with respect to the shield overlay

### ISSUE THREAD

**Issue by michaelbull** [Krealle/Cell_UnitFrames#174]
### Addon Version

1.4.8

### World of Warcraft Version

Retail

### Describe the bug

When using custom texts, the custom text correctly draws **above** the shield texture. As of 1.4.8, the default Health Text now incorrectly draws **beneath** the shield texture.

Below is a picture displaying the problem, whereby the text at the top is the custom text (correct), and the text at the bottom is the health (incorrect).

![image](https://github.com/user-attachments/assets/18158e41-aee7-439f-b87f-9d6a6c566534)

### Steps to reproduce

Enable both a custom text and the default text on the player unit frame.

**Comment by Krealle** [comment]
Can this be resolved by increasing the framelevel in widget setting?

**Comment by michaelbull** [comment]
Unfortunately not, even with a frame level of 100 in the Health Text setting, it still appears underneath the shield overlay. Furthermore, this is the default installation, so I have not intentionally done any custom frame levels, so right now my default insllation of this addon has health text drawing **underneath** the shield overlay.

**Comment by Krealle** [comment]
Hmm, I'll take a look at it tomorrow then

**Comment by Krealle** [comment]
![Image](https://github.com/user-attachments/assets/2d760a11-9c3d-4652-89aa-9a53352c8641)
![Image](https://github.com/user-attachments/assets/2239bb47-6c5b-49ab-b20b-5e7503ef9f5f)
Changing the framelevel for me fixes that issue, are you certain you tried changing the proper framelevel?

**Comment by michaelbull** [comment]
I was changing the level of the Health Text, not the Shield Bar, and it was not working, however I've now started changing the Shield Bar's frame level and confirm it fixes it.

However, I would highlight that this behaviour has changed from a previous version. By default both the Health Text & Shield Bar had a frame level of 10, and before yesterday the text was drawing above the texture, whereas with 1.4.8 onwards it was not the case.

I think that if they both remain at 10 by default and now the health text is underneath the shield texture, this will continue to catch people out going forwards, so your solution does indeed fix it but I suspect somebody else will hit this too.

**Comment by Krealle** [comment]
Hmm it worked fine for me when changing frame level of the text as well - will update the default values so they don't clash.
